export interface Flag {
  id: string;
  name: string;
  emoji: string;
}

export const FLAGS: readonly Flag[] = [
  { id: "ar", name: "Argentina", emoji: "🇦🇷" },
  { id: "au", name: "Australia", emoji: "🇦🇺" },
  { id: "at", name: "Austria", emoji: "🇦🇹" },
  { id: "be", name: "Belgium", emoji: "🇧🇪" },
  { id: "br", name: "Brazil", emoji: "🇧🇷" },
  { id: "ca", name: "Canada", emoji: "🇨🇦" },
  { id: "cl", name: "Chile", emoji: "🇨🇱" },
  { id: "cn", name: "China", emoji: "🇨🇳" },
  { id: "co", name: "Colombia", emoji: "🇨🇴" },
  { id: "hr", name: "Croatia", emoji: "🇭🇷" },
  { id: "cz", name: "Czechia", emoji: "🇨🇿" },
  { id: "dk", name: "Denmark", emoji: "🇩🇰" },
  { id: "ec", name: "Ecuador", emoji: "🇪🇨" },
  { id: "eg", name: "Egypt", emoji: "🇪🇬" },
  { id: "gb-eng", name: "England", emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "fi", name: "Finland", emoji: "🇫🇮" },
  { id: "fr", name: "France", emoji: "🇫🇷" },
  { id: "de", name: "Germany", emoji: "🇩🇪" },
  { id: "gh", name: "Ghana", emoji: "🇬🇭" },
  { id: "gr", name: "Greece", emoji: "🇬🇷" },
  { id: "hu", name: "Hungary", emoji: "🇭🇺" },
  { id: "is", name: "Iceland", emoji: "🇮🇸" },
  { id: "in", name: "India", emoji: "🇮🇳" },
  { id: "id", name: "Indonesia", emoji: "🇮🇩" },
  { id: "ir", name: "Iran", emoji: "🇮🇷" },
  { id: "ie", name: "Ireland", emoji: "🇮🇪" },
  { id: "il", name: "Israel", emoji: "🇮🇱" },
  { id: "it", name: "Italy", emoji: "🇮🇹" },
  { id: "jp", name: "Japan", emoji: "🇯🇵" },
  { id: "ke", name: "Kenya", emoji: "🇰🇪" },
  { id: "kr", name: "South Korea", emoji: "🇰🇷" },
  { id: "mx", name: "Mexico", emoji: "🇲🇽" },
  { id: "ma", name: "Morocco", emoji: "🇲🇦" },
  { id: "nl", name: "Netherlands", emoji: "🇳🇱" },
  { id: "nz", name: "New Zealand", emoji: "🇳🇿" },
  { id: "ng", name: "Nigeria", emoji: "🇳🇬" },
  { id: "no", name: "Norway", emoji: "🇳🇴" },
  { id: "pa", name: "Panama", emoji: "🇵🇦" },
  { id: "py", name: "Paraguay", emoji: "🇵🇾" },
  { id: "pe", name: "Peru", emoji: "🇵🇪" },
  { id: "ph", name: "Philippines", emoji: "🇵🇭" },
  { id: "pl", name: "Poland", emoji: "🇵🇱" },
  { id: "pt", name: "Portugal", emoji: "🇵🇹" },
  { id: "qa", name: "Qatar", emoji: "🇶🇦" },
  { id: "ro", name: "Romania", emoji: "🇷🇴" },
  { id: "ru", name: "Russia", emoji: "🇷🇺" },
  { id: "sa", name: "Saudi Arabia", emoji: "🇸🇦" },
  { id: "gb-sct", name: "Scotland", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "sn", name: "Senegal", emoji: "🇸🇳" },
  { id: "rs", name: "Serbia", emoji: "🇷🇸" },
  { id: "za", name: "South Africa", emoji: "🇿🇦" },
  { id: "es", name: "Spain", emoji: "🇪🇸" },
  { id: "se", name: "Sweden", emoji: "🇸🇪" },
  { id: "ch", name: "Switzerland", emoji: "🇨🇭" },
  { id: "th", name: "Thailand", emoji: "🇹🇭" },
  { id: "tn", name: "Tunisia", emoji: "🇹🇳" },
  { id: "tr", name: "Turkey", emoji: "🇹🇷" },
  { id: "ua", name: "Ukraine", emoji: "🇺🇦" },
  { id: "ae", name: "UAE", emoji: "🇦🇪" },
  { id: "us", name: "USA", emoji: "🇺🇸" },
  { id: "uy", name: "Uruguay", emoji: "🇺🇾" },
  { id: "ve", name: "Venezuela", emoji: "🇻🇪" },
  { id: "gb-wls", name: "Wales", emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { id: "cm", name: "Cameroon", emoji: "🇨🇲" },
  { id: "cr", name: "Costa Rica", emoji: "🇨🇷" },
  { id: "ci", name: "Ivory Coast", emoji: "🇨🇮" },
  { id: "jm", name: "Jamaica", emoji: "🇯🇲" },
  { id: "tz", name: "Tanzania", emoji: "🇹🇿" },
  { id: "dz", name: "Algeria", emoji: "🇩🇿" },
  { id: "bo", name: "Bolivia", emoji: "🇧🇴" },
  { id: "cu", name: "Cuba", emoji: "🇨🇺" },
  { id: "vn", name: "Vietnam", emoji: "🇻🇳" },
  { id: "my", name: "Malaysia", emoji: "🇲🇾" },
  { id: "sg", name: "Singapore", emoji: "🇸🇬" },
  { id: "pk", name: "Pakistan", emoji: "🇵🇰" },
  { id: "bd", name: "Bangladesh", emoji: "🇧🇩" },
  { id: "et", name: "Ethiopia", emoji: "🇪🇹" },
  { id: "ht", name: "Haiti", emoji: "🇭🇹" },
  { id: "sv", name: "El Salvador", emoji: "🇸🇻" },
  { id: "hn", name: "Honduras", emoji: "🇭🇳" },
];

export const PAIR_COUNT = 18;
export const PAIR_FACES = FLAGS.map((flag) => flag.id);
