#!/usr/bin/env node
/**
 * Build the coastline module for Park Your Pirate from Natural Earth 110m land
 * (public domain). Simplifies each polygon so the whole world fits in a few KB.
 *
 *   node scripts/build-land.mjs            # downloads, writes src/.../land.ts
 *   node scripts/build-land.mjs file.json  # use a local GeoJSON instead
 */
import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const URL = "https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/110m/physical/ne_110m_land.json";
const TOLERANCE_DEG = 0.45;
const MIN_POINTS = 5;
const MIN_SPAN_DEG = 1.6;

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "games", "imported", "park-your-pirate", "land.ts");

const source = process.argv[2];
const json = source ? JSON.parse(readFileSync(source, "utf8")) : await (await fetch(URL)).json();

function perpendicular(p, a, b) {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  if (dx === 0 && dy === 0) return Math.hypot(p[0] - a[0], p[1] - a[1]);
  const t = ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (dx * dx + dy * dy);
  const c = Math.max(0, Math.min(1, t));
  return Math.hypot(p[0] - (a[0] + c * dx), p[1] - (a[1] + c * dy));
}

function simplify(points, tolerance) {
  if (points.length <= 2) return points;
  let maxDist = 0;
  let index = 0;
  const first = points[0];
  const last = points[points.length - 1];
  for (let i = 1; i < points.length - 1; i += 1) {
    const d = perpendicular(points[i], first, last);
    if (d > maxDist) {
      maxDist = d;
      index = i;
    }
  }
  if (maxDist <= tolerance) return [first, last];
  const left = simplify(points.slice(0, index + 1), tolerance);
  const right = simplify(points.slice(index), tolerance);
  return left.slice(0, -1).concat(right);
}

const polygons = [];
for (const feature of json.features) {
  const geometry = feature.geometry;
  const shells = geometry.type === "Polygon" ? [geometry.coordinates[0]] : geometry.coordinates.map((p) => p[0]);
  for (const shell of shells) {
    // Closed ring: simplify the open run, then let the renderer close it.
    const open = shell.slice(0, -1);
    const lngs = open.map((p) => p[0]);
    const lats = open.map((p) => p[1]);
    const span = Math.max(Math.max(...lngs) - Math.min(...lngs), Math.max(...lats) - Math.min(...lats));
    if (span < MIN_SPAN_DEG) continue;
    if (Math.max(...lats) < -60) continue; // Antarctica sits under the HUD
    const simple = simplify(open, TOLERANCE_DEG);
    if (simple.length < MIN_POINTS) continue;
    polygons.push(simple.map(([lng, lat]) => [Math.round(lng * 10) / 10, Math.round(lat * 10) / 10]));
  }
}

const total = polygons.reduce((n, p) => n + p.length, 0);
const body = polygons.map((poly) => `  [${poly.map(([x, y]) => `${x},${y}`).join(",")}],`).join("\n");
const file = `/**
 * World coastlines as flat [lng, lat, lng, lat, ...] rings.
 * Generated by scripts/build-land.mjs from Natural Earth 110m land (public domain),
 * simplified to ${TOLERANCE_DEG}° and rounded to 0.1°. ${polygons.length} polygons, ${total} points.
 * Do not edit by hand; rerun the script.
 */
export const LAND: readonly (readonly number[])[] = [
${body}
];
`;
writeFileSync(out, file);
console.log(`wrote ${out}: ${polygons.length} polygons, ${total} points, ${file.length} bytes`);
