#!/usr/bin/env python3
"""Pull club crests from the World XI / soccer-globe dataset into public/crests/."""

from __future__ import annotations

import json
import re
import ssl
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "public" / "crests"
TS_OUT = ROOT / "src" / "minigames" / "crests.ts"
GEOJSON = Path("/tmp/clubs.geojson")
GEOJSON_URL = "https://raw.githubusercontent.com/mapzimus/lab/main/src/lab/world-xi/data/clubs.geojson"
UA = "C5Pairs/0.2 (https://github.com/mapzimus/c5; personal matching game)"

LEAGUES = {
    "Premier League",
    "EFL Championship",
    "La Liga",
    "Serie A",
    "Bundesliga",
    "Ligue 1",
    "Primeira Liga",
    "Eredivisie",
    "Belgian Pro League",
    "Scottish Premiership",
    "Austrian Bundesliga",
    "Swiss Super League",
    "Super League Greece",
    "Süper Lig",
    "Danish Superliga",
    "Allsvenskan",
    "Eliteserien",
    "Ekstraklasa",
    "Czech First League",
    "Major League Soccer",
    "Liga MX",
    "Brasileirão Série A",
    "J1 League",
    "K League 1",
    "A-League Men",
    "Saudi Pro League",
    "Egyptian Premier League",
    "Chinese Super League",
    "Categoría Primera A",
    "Indian Super League",
    "UAE Pro League",
    "League of Ireland Premier Div.",
    "Canadian Premier League",
    "Primera División",
}

SKIP_NAME = re.compile(
    r"\b(B|II|U17|U19|U23|Women|WFC|Ladies|Reserves|Academy|Castilla)\b|(Femení|Femenino|Vrouwen|Féminines)",
    re.I,
)
NON_SLUG = re.compile(r"[^a-z0-9]+")
CTX = ssl.create_default_context()


def slugify(name: str) -> str:
    slug = NON_SLUG.sub("-", name.lower()).strip("-")
    return slug[:60] or "club"


def is_png(path: Path) -> bool:
    return path.read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"


def download(url: str, dest: Path) -> bool:
    if dest.exists() and is_png(dest) and dest.stat().st_size >= 800:
        return True
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(req, timeout=20, context=CTX) as res:
                data = res.read()
            if len(data) < 800 or data[:8] != b"\x89PNG\r\n\x1a\n":
                return False
            dest.write_bytes(data)
            time.sleep(0.35)
            return True
        except urllib.error.HTTPError as err:
            if err.code == 429:
                time.sleep(4 + attempt * 4)
                continue
            return False
        except Exception:
            return False
    return False


def candidates(features: list) -> list[dict]:
    rows = []
    used: set[str] = set()
    for ft in features:
        p = ft["properties"]
        if p.get("gender") != "men" or p.get("league") not in LEAGUES:
            continue
        name = p.get("name") or ""
        crest = p.get("crest")
        if not crest or SKIP_NAME.search(name):
            continue
        qid = str(p.get("qid") or p.get("id") or name)
        ident = slugify(name)
        if ident in used:
            ident = f"{ident}-{qid.lower()}"
        used.add(ident)
        rows.append({"id": ident, "name": name, "file": f"{ident}.png", "url": crest})
    rows.sort(key=lambda row: row["name"].lower())
    return rows


def write_ts(rows: list[dict]) -> None:
    lines = [
        "export interface Crest {",
        "  id: string;",
        "  name: string;",
        "  file: string;",
        "}",
        "",
        "/** Club crests from mapzimus World XI / soccer globe. Regenerated by scripts/fetch-crests.py. */",
        "export const CRESTS: readonly Crest[] = [",
    ]
    for row in rows:
        name = row["name"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  {{ id: "{row["id"]}", name: "{name}", file: "{row["file"]}" }},')
    lines.extend(
        [
            "];",
            "",
            "export const PAIR_COUNT = 18;",
            "export const PAIR_FACES = CRESTS.map((crest) => crest.id);",
            "",
        ]
    )
    TS_OUT.write_text("\n".join(lines))


def main() -> None:
    if not GEOJSON.exists():
        urllib.request.urlretrieve(GEOJSON_URL, GEOJSON)
    features = json.loads(GEOJSON.read_text())["features"]
    rows = candidates(features)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    keep_names = {"ATTRIBUTION.md"}
    ok: list[dict] = []
    print(f"trying {len(rows)} crests", flush=True)
    with ThreadPoolExecutor(max_workers=2) as pool:
        futures = {pool.submit(download, row["url"], OUT_DIR / row["file"]): row for row in rows}
        for i, fut in enumerate(as_completed(futures), start=1):
            row = futures[fut]
            if fut.result():
                ok.append(row)
                keep_names.add(row["file"])
            if i % 50 == 0:
                print(f"  {i}/{len(rows)} checked, {len(ok)} kept", flush=True)
    ok.sort(key=lambda row: row["name"].lower())
    for path in OUT_DIR.iterdir():
        if path.name not in keep_names and path.suffix == ".png":
            path.unlink()
    write_ts(ok)
    print(f"wrote {len(ok)} crests")


if __name__ == "__main__":
    main()
